name: Jekyll site CI

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures you fetch the entire repository history

    - name: Setup Ruby, Jekyll and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Adjust this to match your project's Ruby version

    - name: Build and test Jekyll site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./_site  # Directory where Jekyll builds your site to
        publish_branch: gh-pages  # Target branch to deploy your site
